# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd100b0026cdb51b971757ab965a7ab126933e189acabb78db7cefb23e78c75de87c320737461b6d9c451892a9f440b3ba75887b509de9d0ea198850419ec3e0

test:
  secret_key_base: ce774f7285fa01c5097a7fe389ebdb0cb7b0c8876738a7521668989fdb5439947fc3a7f7f600f9ad3dcafd32494655a1c813c64207e5eb6f370d214086f163fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
